### ISSUE TITLE
Disponibilidade do arquivo json

### ISSUE THREAD

**Issue by bittencourthiago** [vitormattos/a21#1]
Você ainda tem o a21.json? queria saber se poderia me mandar

**Comment by vitormattos** [comment]
Este projeto é bem antigo. Tenho não mas lembro que peguei o json nos arquivos do app. Lembro que dava para ver estes arquivos quando instalava o app.

**Comment by vitormattos** [comment]
Caramba, fiz este código já tem 8 anos! rs....
